apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    user nginx;
    worker_processes auto;
    error_log /var/log/nginx/error.log warn;
    pid /var/run/nginx.pid;

    events {
        worker_connections 1024;
    }

    http {
        include /etc/nginx/mime.types;
        default_type application/octet-stream;
        sendfile on;
        keepalive_timeout 65;

        # Server block for rosenkrmnv.com
        server {
            listen 80;
            server_name rosenkrmnv.com;

            location / {
                root /usr/share/nginx/html/rosenkrmnv;
                index index.html;
            }

            location /stub_status {
                stub_status;
                allow 127.0.0.1;  # Only allow internal access
                deny all;
            }
        }

        # Server block for example.com
        server {
            listen 80;
            server_name example.com;

            location / {
                root /usr/share/nginx/html/example;
                index index.html;
            }

            location /stub_status {
                stub_status;
                allow 127.0.0.1;  # Only allow internal access
                deny all;
            }
        }
    }
