apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html-example
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Welcome to example.com</title>
    </head>
    <body>
      <h1>Hello from example.com</h1>
    </body>
    </html>
